spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/stageDB
  jpa:
    hibernate:
      ddl-auto: update
value:
  rendered: staging
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"